#+INCLUDE: "~/travail/beamer/options.org"
#+LaTeX_CLASS_OPTIONS: [handout]

#+BEAMER_THEME: mytheme

#+BEGIN_EXPORT LATEX
\author{David Gagnon}
\defbeamertemplate*{footline}{shadow theme}{%
\vspace{-2cm}
\hbox{\begin{beamercolorbox}[wd=.5\paperwidth,ht=2.5ex,dp=1.125ex,leftskip=.3cm plus1fil,rightskip=.3cm]{author in head/foot}%
    \usebeamerfont{author in head/foot}\hfill\insertshortauthor\; - Collège d'Alma
\end{beamercolorbox}%

\begin{beamercolorbox}[wd=.5\paperwidth,ht=2.5ex,dp=1.125ex,leftskip=.3cm,rightskip=.3cm plus1fil]{title in head/foot}%
    \usebeamerfont{title in head/foot}\insertshorttitle\hfill%

\end{beamercolorbox}}%
\vskip0pt%
}

\defbeamertemplate*{title page}{customized}[1][]
{
\begin{tikzpicture}[remember picture,overlay]
\fill[structure.fg!50!black]
  ([yshift=50pt]current page.west) rectangle (current page.south east);
\node[anchor=east]
  at ([yshift=80pt,xshift=-10pt]current page.east) (title)
  {\parbox[t]{\textwidth}{\raggedleft%
 \textcolor{structure.fg}{%
{\huge\inserttitle}}}};
\node 
  at ([yshift=-3pt,xshift=65pt]current page.west) (logo)
  {\parbox[t]{.4\paperwidth}{\raggedleft%
    \usebeamercolor[fg]{titlegraphic}\inserttitlegraphic}};
\node[anchor=north east] 
  at ([yshift=-90pt,xshift=0pt]current page.north east) (quote)
  {\parbox[t]{.6\paperwidth}{
    \usebeamerfont{institute}\textcolor{white}{
   \large «\it We have set a clear goal vital to the next chapter of America's story in space: sending humans to Mars by the 2030s and returning them safely to Earth, with the ultimate ambition to one day remain there for an extended time.»
\\ \\ 
{{\large\raggedright --- Barack Obama}\\ \parbox{0.55cm}{\color{structure.fg!50!black}}\footnotesize \hspace{12pt} (1961-)}
}}};
\end{tikzpicture}

}
\title{Chapitre 9 \\ Les sources de champ magnétique}
\titlegraphic{\includegraphics[width=4.84cm]{figures/mars.jpg}}
\maketitle
#+END_EXPORT

* À faire							   :noexport:
* Démos								   :noexport:
* Table des matières
** 
\begin{enumerate}
\item Champ magnétique pour un fil
\item Loi de Biot-Savart
\item Force magnétique entre des fils conducteurs parallèles
\item Théorème d'Ampère
\item Force magnétique entre deux dipôles magnétiques
\item Champ magnétique terrestre
\end{enumerate}

* Champ magnétique créé par un fil
** Champ magnétique créé par un fil
\begin{columns}[T]
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.65\textheight,keepaspectratio]{figures/9-1a.png}
\caption*{{\color{blue}Figure 9.1(a)} La configuration de la limaille de fer autour d'un long conducteur rectiligne parcouru par un courant.}
\end{figure}
\end{column}
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.45\textheight,keepaspectratio]{figures/9-1c.png}
\caption*{{\color{blue}Figure 9.1(c)} Une des lignes de champ magnétique associé à un courant sortant de la page (point) et entrant dans la page (croix).}
\end{figure}
\end{column}
\end{columns}

** Règle de la main droite
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.45\textheight,keepaspectratio]{figures/9-2.png}
\caption*{{\color{blue}Figure 9.2} Sens de $\vec{B}$ obtenu en utilisant la règle de la main droite.}
\end{figure}

\begin{block}{\B{PROP} Règle de la main droite donnant le sens de $\vec{B}$}
Si on saisit le fil avec la main droite, le pouce étant orienté dans le sens du courant, les autres doigts s'enroulent dans le sens du champ magnétique.
\end{block}

** Champ magnétique créé par un fil infini
\begin{block}{\B{PROP} Champ magnétique produit par un fil rectiligne de longueur infinie}
$$B=\frac{\mu_0I}{2\pi R}$$
\end{block}

** Exemple
\begin{exampleblock}{\B{EX} 9.1}
Soit deux longs fils rectilignes parallèles distants de $3\centi\meter$. Ils sont traversés par les courants $I_1=3\ampere$ et $I_2=5\ampere$, de sens opposés.
\begin{enumerate}[<+->][a]
\item Déterminer le champ magnétique résultant au point P.
\item En quel point, autre qu'à l'infini, le champ magnétique est-il nul?
\end{enumerate}
\end{exampleblock}

** Exemple (Suite)
\begin{exampleblock}{\B{EX} 9.1}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.75\textheight,keepaspectratio]{figures/9-3.png}
\end{figure}
\end{exampleblock}

* Loi de Biot-Savart
** Loi de Biot-Savart
\begin{columns}[T]
\begin{column}{.6\textwidth}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.75\textheight,keepaspectratio]{figures/9-5b.png}
\end{figure}
\end{column}
\begin{column}{.4\textwidth}
\vspace{1cm}
{\color{blue} Figure 9.5(b)} Le champ magnétique $d\vec{B}$ créé par l'élément de courant $Id\vec{\ell}$ est perpendiculaire à la fois au segment de droite allant de l'élément au point où on calcule le champ et à $d\vec{\ell}$.
\end{column}
\end{columns}

** Loi de Biot-Savart (Suite)
\begin{itemize}[<+->]
\item $\vec{u}_r$ est un vecteur unitaire pointant de l'élément de courant vers le point où on calcule le champ magnétique produit par celui-ci;
\item $d\vec{B}\perp d\vec{\ell}$ et $d\vec{B}\perp \vec{u}_r$;
\item $dB\propto \frac{1}{r^2}$;
\item $dB\propto I$, $dB\propto d\ell$ et $dB\propto \sin{\theta}$.
\end{itemize}

** Loi de Biot-Savart (Suite)
d'où

\begin{block}{\B{PROP} Loi de Biot-Savart}
$$d\vec{B}=\frac{\mu_0}{4\pi}\frac{Id\vec{\ell}\times\vec{u}_r}{r^2}$$

où

$d\ell$: longueur d'un bout du conducteur;

$I$: courant dans le conducteur;

$\vec{u}_r$: vecteur unitaire pointant de l'élément de courant vers le point où on calcule le champ qu'il produit;

$dB$: grandeur du champ magnétique produit par le bout de conducteur $d\ell$ parcouru par un courant $I$ à une distance $r$;

$\mu_0$: perméabilité du vide $4\pi\times 10^{-7}\frac{\newton}{\ampere^2}$

\end{block}

** Calcul de $\vec{B}$ avec la loi de Biot-Savart
\begin{equation*}
 \vec{B} = \displaystyle\int d\vec{B}\Rightarrow
  \begin{cases}
   B_x=\displaystyle\int dB_x \\
   B_y=\displaystyle\int dB_y \\
   B_z=\displaystyle\int dB_z
  \end{cases}
\end{equation*}

** Champ magnétique créé par un fil fini
\begin{columns}[T]
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[scale=0.45]{figures/9-10a.png}
\caption*{{\color{blue} Figure 9.10} Champ magnétique produit par une partie du fil au point P.}
\end{figure}

\end{column}
\begin{column}{.5\textwidth}
\begin{itemize}[<+->]
\item \alert{Remarquez le choix judicieux des axes!}
\item $B_x=B_y=0$;
\item $d\ell=dx$ donc $||d\vec{\ell}\times\vec{u}_r||=u_rd\ell\sin{\theta}=dx\sin{\theta}$
\item $B_z=\displaystyle\int dB_z=\frac{\mu_0I}{4\pi}\displaystyle\int \frac{\sin{\theta}dx}{r^2}$
\end{itemize}
\end{column}
\end{columns}~

** Champ magnétique créé par un fil fini (Suite)
\begin{columns}[T]
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[scale=0.45]{figures/9-10a.png}
\caption*{{\color{blue}Figure 9.10} Champ magnétique produit par une partie du fil au point P.}
\end{figure}
\end{column}
\begin{column}{.5\textwidth}
\alert{Remarque: $x$, $\theta$ et $r$ sont tous dépendants.}

On exprime $r$ et $dx$ en fonction de $\theta$:

\begin{itemize}[<+->]
\item $\sin{\theta}=\frac{R}{r}$ d'où $r^2=\frac{R^2}{\sin^2{\theta}}$
\item $\tan{\theta=\frac{R}{-x}}$ d'où $x=-R\cot{\theta}$
\item \begin{aligned}dx&=-R \left( -\mathrm{cosec}^2 \theta d\theta \right)\\&=R\mathrm{cosec}^2 \theta d\theta\end{aligned}
\end{itemize}
\end{column}
\end{columns}

** Champ magnétique créé par un fil fini (Suite)
\begin{figure}[H]
\centering
\includegraphics[scale=0.45]{figures/9-10b.png}
\caption*{{\color{blue} Figure 9.10(b)} Si on choisit $\theta$ comme variable d'intégration, les bornes d'intégration sont $\theta_1$ et $\theta_2$.}
\end{figure}

** Champ magnétique créé par un fil fini (Suite) 
\begin{align*}
B&=\frac{\mu_0I}{4\pi}\displaystyle\int_{\theta_1}^{\theta_2}\frac{R\mathrm{cosec}^2\theta\sin{\theta}d\theta}{R^2/\sin^2{\theta}}\\
&=\frac{\mu_0I}{4\pi R}\displaystyle\int_{\theta_1}^{\theta_2}\sin{\theta}d\theta
\end{align*}

d'où

\begin{block}{\B{PROP} Champ magnétique produit par un fil rectiligne de longueur finie}
$$B=\frac{\mu_0I}{4\pi R}\left( \cos{\theta_1}-\cos{\theta_2} \right)$$
\end{block}

** Champ magnétique créé par un fil infini
\begin{figure}[H]
\centering
\includegraphics[scale=0.45]{figures/9-10b.png}
\caption*{{\color{blue} Figure 9.10(b)} Si on choisit $\theta$ comme variable d'intégration, les bornes d'intégration sont $\theta_1$ et $\theta_2$.}
\end{figure}

\begin{itemize}[<+->]
\item $\theta_1=0$ et $\theta_2=\pi$;
\item \begin{aligned}
B&=\frac{\mu_0I}{4\pi R}\left( \cos{\theta_1}-\cos{\theta_2} \right)\\&=\frac{\mu_0I}{4\pi R}\left( 1-\left( -1 \right) \right)
\end{aligned}
\end{itemize}

** Champ magnétique créé par un fil infini (Suite)
d'où
\begin{block}{\B{PROP} Champ magnétique produit par un fil rectiligne de longueur infinie}
$$B=\frac{\mu_0I}{2\pi R}$$
\end{block}

** Méthode de résolution
Voir p. 361.

** Ondes électromagnétiques
\begin{itemize}
\item $\mu_0$: perméabilité du vide $4\pi\times 10^{-7}\frac{\newton}{\ampere^2}$;
\item $\epsilon_0$: permittivité du vide $8,85\times 10^{-12}\frac{\farad}{\meter}$;
\item $\frac{1}{\sqrt{\epsilon_0\mu_0}}=3\times 10^{8}\frac{\meter}{\second}=c$.
\end{itemize}

\begin{figure}[H]
\captionsetup{justification=centering}
\centering
\includegraphics[width=\textwidth,height=0.62\textheight,keepaspectratio]{figures/13-6.png}
\caption*{{\color{blue}Figure 13.6} Une onde électromagnétique.}
\end{figure}

** Ondes électromagnétiques (Suite)
\begin{figure}[H]
\captionsetup{justification=centering}
\centering
\includegraphics[width=\textwidth,height=0.85\textheight,keepaspectratio]{figures/13-15.png}
\caption*{{\color{blue}Figure 13.15} Le spectre des longueurs d'ondes des ondes électromagnétique.}
\end{figure}

** Exemple 9.3                                                    :noexport:
\begin{exampleblock}{\B{EX} 9.3}
Un courant de $2A$ circule dans le fil illustré à la figure 9.8.  Calculer le champ magnétique produit par ce courant au point A en utilisant directement la loi de Biot-Savart.
\end{exampleblock}

** Exemple 9.3 (Suite)                                            :noexport:
\begin{exampleblock}{\B{EX} 9.3}
\begin{figure}[H]
\centering
\includegraphics[scale=0.6]{figures/9-8.png}
\caption*{{\color{blue}Figure 9.8} Ex 9.3}
\end{figure}
\end{exampleblock}

** Exemple - Boucle de courant
\begin{exampleblock}{\B{EX} Boucle de courant}
\begin{columns}[T]
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.85\textheight,keepaspectratio]{figures/9-14c.png}
\caption*{{\color{blue}Figure 9.14(c)} Le champ magnétique produit par une boucle de courant.}
\end{figure}
\end{column}
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.7\textheight,keepaspectratio]{figures/9-12.png}
\caption*{{\color{blue}Figure 9.12} Champ magnétique produit par une boucle de courant.}
\end{figure}
\end{column}
\end{columns}
\end{exampleblock}

** Champ magnétique au centre d'une boucle circulaire
\begin{exampleblock}{\B{EX} Boucle de courant}
\begin{columns}[T]
\begin{column}{.6\textwidth}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.55\textheight,keepaspectratio]{figures/9-12.png}
\caption*{{\color{blue}Figure 9.12} Champ magnétique produit par une boucle de courant.}
\end{figure}

\end{column}
\begin{column}{.4\textwidth}
\begin{itemize}[<+->]
\item On a $d\vec{B}=\displaystyle\frac{\mu_0}{4\pi}\frac{Id\vec{\ell}\times\vec{u}_r}{r^2}$. Donc, $dB=\displaystyle\frac{\mu_0}{4\pi}\frac{Id\ell\sin{\theta}}{r^2}$
\item De plus, pour tous les couples de $d\vec{\ell}$ et $\vec{u}_r$, $\theta=90\degree$.
\item $dl=Rd\alpha$

avec
$\alpha$ : $0 \rightarrow 2\pi$

pour parcourir toute la boucle.

\item Aussi, $r=R$.
\end{itemize}
\end{column}
\end{columns}
\end{exampleblock}

** Champ magnétique au centre d'une boucle circulaire
\begin{exampleblock}{\B{EX} Boucle de courant}
donc

\begin{eqnarray*}
B&=&\displaystyle\int dB\\
&=&\frac{\mu_0I}{4\pi R^2}\displaystyle\int \sin{\theta}d\ell\\
&=&\frac{\mu_0I\sin{90\degree}}{4\pi R^2}\displaystyle\int_0^{2\pi} Rd\alpha\\
&=&\frac{\mu_0I}{4\pi R^2}\times 2\pi R\\
&=&\frac{\mu_0I}{2R}
\end{eqnarray*}
\end{exampleblock}

** Champ magnétique au centre d'une boucle circulaire
\begin{block}{\B{PROP} Champ magnétique produit au centre d'une boucle circulaire de courant}
$$B=\frac{\mu_0I}{2R}$$
\end{block}

** Dipôle électrique et dipôle magnétique
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.7\textheight,keepaspectratio]{figures/9-17.png}
\caption*{{\color{blue}Figure 9.17} Les lignes de champ pour (a) un dipôle électrique et (b) un dipôle magnétique.}
\end{figure}

** Électroaimant et aimants permanents
\begin{block}{\B{DEF} Électroaimant}
Un électroaimant est un aimant qui tire son aimantation du courant électrique qui le traverse.
\end{block}

\begin{block}{\B{DEF} Aimant permanent}
Un aimant permanent tire son aimantation du mouvement des électrons dans les atomes qui le composent.
\end{block}

** Détecteur ATLAS au LHC
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.65\textheight,keepaspectratio]{figures/9-36.png}
\caption*{{\color{blue}Figure 9.36} Le détecteur ATLAS, au Large Hadron Collider, contient le plus grand électroaimant toroïdal au monde.  Ses spires sont regroupées en huit groupes qu'on voit sur la photo.  L'aimant produit un champ maximal de $3,9\tesla$ dans l'air grâce à un courant de plusieurs milliers d'ampères.}
\end{figure}

* Force magnétique entre des fils conducteurs parallèles
** Force magnétique entre des fils conducteurs parallèles
\begin{columns}[T]
\begin{column}{.5\textwidth}
\begin{figure}[H]
\centering
\includegraphics[scale=0.4]{figures/9-4.png}
\caption*{{\color{blue} Figure 9.4} Forces magnétiques attractives si le courant est dans le même sens pour les deux fils.}
\end{figure}
\end{column}
\begin{column}{.5\textwidth}
\begin{align*}
\vec{F}_{21}&=I_2\vec{\ell}_2\times\vec{B}_1\\
\Rightarrow F_{21}&=I_2\ell_2B_1\\
&=I_2\ell_2 \frac{\mu_0I_1}{2\pi d}
\end{align*}
\begin{block}<2->{\B{PROP} Module de la force magnétique par unité de longueur entre deux fils parallèles}
$$\frac{F_B}{\ell}=\frac{\mu_0I_1I_2}{2\pi d}$$
\end{block}
\end{column}
\end{columns}

* Théorème d'Ampère
** Théorème d'Ampère
\begin{block}{\B{PROP} Théorème d'Ampère}
$$\displaystyle\oint\vec{B}\cdot d\vec{\ell}=\mu_0\displaystyle\sum I$$
\end{block}

\begin{figure}[H]
\centering
\includegraphics[scale=0.4]{figures/9-30.png}
\caption*{{\color{blue}Figure 9.30} L'intégrale $\oint\vec{B}\cdot d\vec{\ell}$ sur un parcours fermé qui entoure le courant est égale à $\mu_0I$ pour tout parcours entourant le courant.}
\end{figure}

** Théorème d'Ampère (Suite)
\begin{figure}[H]
\centering
\includegraphics[scale=0.3]{figures/9-31.png}
\caption*{{\color{blue}Figure 9.31} Le parcours fermé n'entoure pas le courant donc $\oint\vec{B}\cdot d\vec{\ell}=0$.}
\end{figure}

\alert{Attention: ça ne signifie pas que B=0 sur le parcours.}

** Exemple - Champ magnétique produit par un solénoïde
\begin{exampleblock}{\B{EX} 9.12 Champ magnétique produit par un solénoïde}
Un très long solénoïde compte $n$ spires par unité de longueur et il est parcouru par un courant $I$. Déterminer le module du champ magnétique produit à l'intérieur de ce solénoïde.
\end{exampleblock}

** Exemple - Champ magnétique produit par un solénoïde (Suite)
\begin{exampleblock}{\B{EX} 9.12 Champ magnétique produit par un solénoïde}
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.25\textheight,keepaspectratio]{figures/9-34.png}
\caption*{{\color{blue}Figure 9.34} Le champ magnétique à l'intérieur d'un long solénoïde est uniforme et nul à l'extérieur.}
\end{figure}

\begin{array*}
\displaystyle\oint\vec{B}\cdot d\vec{\ell}=\displaystyle\oint_A^B\vec{B}\cdot d\vec{\ell}+\displaystyle\oint_B^C\vec{B}\cdot d\vec{\ell}+\displaystyle\oint_C^D\vec{B}\cdot d\vec{\ell}+\displaystyle\oint_D^A\vec{B}\cdot d\vec{\ell}\\
&\displaystyle\oint\vec{B}\cdot d\vec{\ell}=B\int_B^Ad\ell=\mu_0nLI
\end{array}

d'où $$B=\mu_0nI$$
\end{exampleblock}

** Champ magnétique produit par un solénoïde
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.35\textheight,keepaspectratio]{figures/9-21b.png}
\caption*{{\color{blue}Figure 9.21(b)} Champ mangétique à l'intérieur d'un long solénoïde.}
\end{figure}

\begin{block}{\B{PROP} Module du champ magnétique à l'intérieur d'un long solénoïde}
$$B=\mu_0nI$$

où

$n=\frac{N}{\ell}$: nombre de spires par unité de longueur. 
\end{block}

** Champ magnétique produit par un solénoïde (Suite)
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.25\textheight,keepaspectratio]{figures/9-20.png}
\caption*{{\color{blue}Figure 9.20(a)} La configuration de la limaille de fer dans le cas de sept spires.  {color{blue} (b)} Les lignes de champ magnétique dans le cas de cinq spires.}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.25\textheight,keepaspectratio]{figures/9-21.png}
\caption*{{\color{blue}Figure 9.21} Le champ magnétique à l'intérieur d'un long solénoïde est uniforme.  À l'extérieur, il est pratiquement nul.}
\end{figure}

** Exemple 9.11
\begin{exampleblock}{\B{EX} 9.11}
\begin{columns}[T]
\begin{column}{.4\textwidth}
\vspace{0.1cm}
Un conducteur rectiligne infini de rayon $R$ est parcouru par un courant $I$.  Déterminer le module du champ magnétique à une distance $r$ du centre du conducteur pour (a) $r>R$ et (b) $r<R$.  On suppose que le courant est distribué uniformément sur la section transversale du conducteur.
\end{column}
\begin{column}{.4\textwidth}
\begin{figure}[H]
\centering
\includegraphics[scale=0.3]{figures/9-33.png}
\caption*{{\color{blue}Figure 9.33} Ex 9.11}
\end{figure}
\end{column}
\end{columns}
\end{exampleblock}



* Force magnétique entre deux dipôles magnétiques
** La force magnétique entre deux dipôles magnétiques
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.65\textheight,keepaspectratio]{figures/9-37.png}
\caption*{{\color{blue}Figure 9.37(a)} La force magnétique s'exerçant sur l'élément de courant de la boucle 1 placée dans le champ magnétique dipolaire de la boucle 2.  {\color{blue}(b)} La force magnétique s'exerçant sur l'élément de courant de la boucle 2 placée dans le champ magnétique dipolaire de la boucle 1.}
\end{figure}

* Champ magnétique terrestre
** Le champ magnétique terrestre
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.85\textheight,keepaspectratio]{figures/9-49.png}
\caption*{{\color{blue}Figure 9.49} Le champ magnétique terrestre correspond essentiellement au champ d'un dipôle.}
\end{figure}

** La source du champ mangétique terrestre
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.7\textheight,keepaspectratio]{figures/9-54.png}
\caption*{{\color{blue}Figure 9.54} Le champ magnétique terrestre est produit par des courants dans le noyau externe liquide.}
\end{figure}

** Vent solaire
\begin{figure}[H]
\centering
\includegraphics[width=\textwidth,height=0.85\textheight,keepaspectratio]{figures/9-56.png}
\caption*{{\color{blue}Figure 9.56} Le champ magnétique terrestre observé à grande échelle est très différent de celui d'un dipôle.}
\end{figure}
